# Generated by Django 6.0.7 on 2026-07-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_archived_tag_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description_spanish',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
