# Generated by Django 6.0.7 on 2026-07-13 06:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activity_description_spanish_activity_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
