# Generated by Django 6.0.7 on 2026-07-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_line_song_verse_alter_tag_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line',
        ),
        migrations.DeleteModel(
            name='Verse',
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_phonetic',
            field=models.TextField(blank=True),
        ),
    ]
