# Generated by Django 6.0.7 on 2026-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_line_delete_verse_song_lyrics_phonetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
