# Generated by Django 6.0.7 on 2026-07-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_song_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lyrics', models.TextField(blank=True)),
                ('lyrics_spanish', models.TextField(blank=True)),
                ('lyrics_phonetic', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics_phonetic',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics_spanish',
        ),
    ]
