# Generated by Django 6.0.7 on 2026-07-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_verse_remove_song_lyrics_remove_song_lyrics_phonetic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='verse',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='api.song'),
        ),
    ]
