# Generated by Django 6.0.7 on 2026-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_activity_created_date_activity_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
